# Permalinks
permalink:           pretty

# Setup
title:               Maxwell Shinn's Homepage
tagline:             
url:                 http://www.maxshinnpotential.com
baseurl:             http://www.maxshinnpotential.com


# About/contact
author:
  name:              Max Shinn
  url:               https://www.maxshinnpotential.com
  email:             admin@maxshinnpotential.com

# Custom vars
version:             2.0.0
#github:
#  repo:              https://github.com/poole/poole

